build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-debian:bookworm"
  aarch64: "ghcr.io/home-assistant/aarch64-base-debian:bookworm"
args:
  LANGFUSE_VERSION: "4.0.0"
  CLICKHOUSE_VERSION: "26.4.1.2007"
  SEAWEEDFS_VERSION: "3.79"
