#!/usr/bin/env bash
source /data/secrets.env
exec redis-server --bind 127.0.0.1 --port 6379 --requirepass "${REDIS_PASSWORD}" --dir /data/redis --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
