name: "Roon Spotify Add-on"
version: "0.2.0"
slug: "roon_spotify_addon"
description: "Roon Server with a Spotify Connect endpoint"
arch:
  - aarch64
  - amd64
init: false
host_network: true
map:
  - "data:rw"
modules:
  - snd-aloop
devices:
  - /dev/snd
options:
  spotify_username: ""
  spotify_password: ""
  spotify_device_name: "Roon"
schema:
  spotify_username: "str"
  spotify_password: "password"
  spotify_device_name: "str"
